// automatically generated by the FlatBuffers compiler, do not modify

package com.fhj.byteparse.flatbuffers;

@SuppressWarnings("unused")
public final class MessageData {
  private MessageData() { }
  public static final byte NONE = 0;
  public static final byte TextMessage = 1;
  public static final byte ImageMessage = 2;
  public static final byte AudioMessage = 3;
  public static final byte VideoMessage = 4;
  public static final byte FileMessage = 5;

  public static final String[] names = { "NONE", "TextMessage", "ImageMessage", "AudioMessage", "VideoMessage", "FileMessage", };

  public static String name(int e) { return names[e]; }
}

