// automatically generated by the FlatBuffers compiler, do not modify

package com.fhj.byteparse.flatbuffers;

@SuppressWarnings("unused")
public final class MessageType {
  private MessageType() { }
  public static final long DISCOVERY = 0;
  public static final long Text = 1;
  public static final long IMAGE = 2;
  public static final long AUDIO = 3;
  public static final long VIDEO = 4;
  public static final long FILE = 5;
  public static final long MULTI = 6;
  public static final long CLOSE = 7;
}

