// automatically generated by the FlatBuffers compiler, do not modify

package com.fhj.byteparse.flatbuffers;

@SuppressWarnings("unused")
public final class MessageStatus {
  private MessageStatus() { }
  public static final int SUCCESS = 0;
  public static final int FAILED = 1;
  public static final int SENDING = 2;
  public static final int READ = 3;

  public static final String[] names = { "SUCCESS", "FAILED", "SENDING", "READ", };

  public static String name(int e) { return names[e]; }
}

